openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/JMINHOWSAND682/TEST/1.0.0
info:
  description: 製品在庫を管理するAPI
  version: "1.0.0"
  title: Inventory API
tags:
  - name: Products
    description: 商品管理
  - name: InventoryProducts
    description: 在庫管理
paths:
  /products:
    get:
      tags:
        - Products
      summary: 商品情報の取得
      operationId: getProducts
      description: |
        すべての商品情報を取得する
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/400BadRequest'
    post:
      tags:
        - Products
      summary: 商品の登録
      operationId: createProducts
      description: |
        商品を新規に登録する
      requestBody:
        description: 登録する商品情報
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Products'
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/201Created'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/400BadRequest'
  /products/{id}:
    get:
      tags:
        - Products
      summary: IDによる商品情報の取得
      operationId: getProductsById
      description: |
        指定した商品IDと一致する商品情報を取得する
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/404NotFound'
    patch:
      tags:
        - Products
      summary: 商品IDによる商品情報の更新
      operationId: patchProductsById
      description: |
        指定した商品IDと一致する商品情報を更新する
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        description: 登録する商品情報
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Products'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/200OK'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/400BadRequest'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/404NotFound'
    delete:
      tags:
        - Products
      summary: 商品IDによる商品情報の削除
      operationId: deleteProductsById
      description: |
        指定した商品IDと一致する商品情報を削除する
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/200OK'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/404NotFound'
  /inventory-products:
    get:
      tags:
        - InventoryProducts
      summary: 在庫情報の取得
      operationId: getInventoryItems
      description: |
        すべての在庫情報を取得する
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/200OK'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/400BadRequest'
    post:
      tags:
        - InventoryProducts
      summary: 在庫情報の登録
      operationId: createInventoryItem
      description: |
        在庫情報を新規に登録する
      requestBody:
        description: 登録する部品情報
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryProducts'
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/201Created'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/400BadRequest'
  /inventory-products/{productId}:
    get:
      tags:
        - InventoryProducts
      summary: 商品IDによる在庫情報の取得
      operationId: getInventoryItemsByProductId
      description: |
        指定した商品IDと一致する在庫情報を取得する
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InventoryProducts'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/404NotFound'
    patch:
      tags:
        - InventoryProducts
      summary: 商品IDによる在庫情報の更新
      operationId: patchInventoryItemsByProductId
      description: |
        指定した商品IDと一致する在庫情報を更新する
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        description: 登録する部品情報
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchRequestBody'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/200OK'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/400BadRequest'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/404NotFound'
    delete:
      tags:
        - InventoryProducts
      summary: 商品IDによる在庫情報の削除
      operationId: deleteInventoryItemsByProductId
      description: |
        指定した商品IDと一致する在庫情報を削除する
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/200OK'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/404NotFound'
components:
  schemas:
    Products:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 'Gear main'
    InventoryProducts:
      type: object
      required:
        - id
        - product_Id
        - quantity
        - history
      properties:
        id:
          type: integer
          example: 1
        product_Id:
          type: integer
          example: 1
        quantity:
          type: integer
          example: 1000
        history:
          type: string
          example: '2020-01-31T23:59:59+09:00'
          format: date-time
    PatchRequestBody:
      type: object
      properties:
        productName:
          type: string
          example: 'Gear assy 1'
        quantity:
          type: integer
          example: 2000
    200OK:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: 'Successful operation'
    201Created:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: 'New inventory item was successfully created'
    400BadRequest:
      type: object
      required:
        - status
        - message
        - errors
      properties:
        status:
          type: string
          example: 'BAD_REQUEST'
        message:
          type: string
          example: 'Bad request'
        errors:
          type: array
          items:
            oneOf:
              - type: object
                properties:
                  field:
                    type: string
                    example: 'name'
                  message:
                    type: string
                    example: '空白は許可されていません'
              - type: object
                properties:
                  field:
                    type: string
                    example: 'name'
                  message:
                    type: string
                    example: '0 から 30 の間のサイズにしてください'

    404NotFound:
      type: object
      required:
        - path
        - error
        - timestamp
        - message
        - status
      properties:
        path:
          type: string
          example: '/products/0'
        error:
          type: string
          example:
            'Not Found'
        timestamp:
          type: string
          example:
            '2024-03-26T22:19:19.376914800+09:00[Asia/Tokyo]'
          format: date-time
        message:
          type: string
          example: 'Product ID:0 does not exist'
        status:
          type: string
          example:
            '404'
