name: Java CI with Gradle
on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_URL: ${{secrets.SECRET_SPRING_DATASOURCE_URL}}
      SPRING_DATASOURCE_USERNAME: ${{secrets.SECRET_SPRING_DATASOURCE_USERNAME}}
      SPRING_DATASOURCE_PASSWORD: ${{secrets.SECRET_SPRING_DATASOURCE_PASSWORD}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Docker
        run: docker compose up -d
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Conduct Tests
        run: TZ=Asia/Tokyo ./gradlew test
        if: always()

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: "**/build/test-results/test/TEST-*.xml"

      - name: Notifications for Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          status: ${{ job.status }}
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Playwright Browsers
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Spring Boot in Background
        run: ./gradlew bootRun &

      - name: Wait for Spring Boot to be ready
        run: npx wait-on http://localhost:8080/index.html

      - name: Run Playwright tests
        run: npx playwright test
